# -*- coding: utf-8 -*-
"""caesar_cipher

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HpcTl-cA__ko15vfwuey2OtRoVjyBR_-
"""

import string

def caesar_encrypt(data,key):    
    res = ""    
    for x in range(len(data)):        
       if data[x].isupper():            
          pos = string.ascii_uppercase.index(data[x].replace(" ", "")) + key
          pos = pos % 26            
          res += string.ascii_uppercase[pos]
       elif data[x].islower():            
          pos = string.ascii_lowercase.index(data[x].replace(" ", "")) + key       
          pos = pos % 26            
          res += string.ascii_lowercase[pos]
       else:            
          res += data[x].replace(" ", "")   
    return res

def caesar_decrypt(data,key):    
    res = ""    
    for x in range(len(data)):        
       if data[x].isupper():            
          pos = string.ascii_uppercase.index(data[x]) - key            
          pos = pos % 26            
          res += string.ascii_uppercase[pos]        
       elif data[x].islower():            
          pos = string.ascii_lowercase.index(data[x]) - key            
          pos = pos % 26            
          res += string.ascii_lowercase[pos]        
       else:            
          res += data[x]    
    return res

enkripsi = caesar_encrypt("caesar cipher", 1)
dekripsi = caesar_decrypt(enkripsi, 1)
print(enkripsi)
print(dekripsi)